### ISSUE TITLE
List of missing features from Advantage 360 app

### ISSUE THREAD

**Issue by tubadan33** [KinesisCorporation/SmartSetApps#13]
Just received my Advantage 360 and frankly I'm appalled by the lack of features in the smart set 360 app. Especially for a $400 product.

- No indication that macros are set on a specific key, in the smartset2 app it was clear that a key had a macro set on it by being indicated with a blue outline, this is now gone.
- Still no home row mod support, this is an awesome feature that would be amazing to have
- Can't reset entire layer, have to reset key by key or lose changes to entire profile
- Ugly UI, more of a preference, but for a $400 product its very outdated 
- Very incomplete list of shifted symbols
- No search for keys when assigning, you have to go hunt in the side panel for the key that you want

I'm sure there are more but these are just the ones that stood out to me immediately. I don't think I'm using the software incorrectly.  It makes me very sad that Kinesis can deliver such an amazing piece of hardware with such lacking software.

**Comment by KinesisCorporation** [comment]
Hi Daniel,

I'm sorry the SmartSet App has come up short of your expectations and we appreciate the feedback. We are a hardware-first company but we believe we've been making incremental improvements to the SmartSet App over the past few years, but our priority is to make something lightweight that is "no-install" and doesn't require any special drivers so it will always fall short of the Razer, Logitech's of the world.

To respond to your specific feedback:

- Macro assignments: We changed how macros are triggered in the 360 with a view to making it more flexible/powerful (triggers are actions rather than positions) which rendered the old display mechanism meaningless. That's why we added the Macro Repository to the 360 App to see what macros are where at a glance.
- Not sure what you mean by "home row mod support" but I suspect that's a feature that isn't supported in the keyboard itself, versus the App specifically.
- Shifted Symbols: The App is intended to offer access to all actions that are supported by the keyboard. A "shifted" action is functionally a macro (ie two key combo) so those are handled differently. If there are actual tokens that are in the User Manual but not the App please let us know.
- UI: We will provide this feedback to the team and please feel free to send us some examples of similar software you like.
- Search function: We can explore what it would take to add a Search function to the App, good idea!
- Layer Reset: This is a great suggestion! We'll look to add it to the next update.

**Comment by tubadan33** [comment]
Home row mods allow a user to use the home row keys as modifiers when held down. So (on colemak) the left home row is 'arstg', 't' can be set to type 't' when tapped or to be used as a modifier when held down. There is a 'hold-tap' feature, but it doesn't seem to support using the windows key as a modifier, and there is no interrupt disabling feature, so if I have 't' tap-holding to shift, and press 't' then 'h' while still holding 't' (which happens often when typing quickly) 't' will not get sent and just 'h' will. If home row mods were properly supported (read more [here](https://zmk.dev/docs/behaviors/mod-tap) then a lot of keys can be done away with completely. 

A complete list of shifted symbols would make configuration much easier especially when defining symbol layers. Having to use macros is just an unnecessary complication. 

Thank you for your response. I really do love the keyboard, but have just been beyond disappointed with the software. Perhaps I should return it and get the bluetooth pro edition with zmk support, but its already a very expensive keyboard, was hoping for a better solution than that.

**Comment by KinesisCorporation** [comment]
It sounds like you are looking for ZMK level Mod-Tap. If that's a critical feature you should definitely consider the Pro. The SmartSet keyboard has always been focused on onboard programmability so we've never been able to implement an equivalent version of _that_ feature as its found on QMK/ZMK.

Have you experimented with customizing the layout for the Pro using the web-based [Keymap Editor](https://kinesiscorporation.github.io/Adv360-Pro-GUI/)? If you prefer that then it seems the Pro version is definitely the keyboard for you.

Regarding shifted characters, it is our understanding that many/most/all "shifted symbols" don't have stand-alone USB codes so they only exist as a key combo. Hence the SmartSet keyboard treats them as macros rather than "tokens". I am not totally sure how ZMK manages this.

The Pro and the SmartSet are two VERY different electronic architectures which prioritize different features for the benefit of slightly different audiences. Neither keyboard does everything perfectly, but hopefully one of them will meet most of your needs.

**Comment by tubadan33** [comment]
After some investigation the 360 Pro is just not for me, I suppose I will just have to live with it. Thank you for your time.
