### ISSUE TITLE
App Closes Immediately after clicking "Configure"

### ISSUE THREAD

**Issue by moosey-moose** [KinesisCorporation/SmartSetApps#15]
Advantage 360 US 
Profile 1
Remaps 2
Macros 1
NKRO Off
L Firmware 1.0.71
R Firmware 1.0.71
Bootloader 1.3
www.kinesis.com/support/kb360

Windows 11, after entering vdrive mode and opening the smartset app, it finds the keyboard but immediately closes once I click configure.

**Comment by Omniscently** [comment]
Is this on a personal machine or one provided by an employer/organization? 

The App could be crashing, or it may be getting stopped due to security concerns. 

If the App is crashing, there could be corruption in the V-Drive, causing the App to break, or programming that is breaking the App. 

Can you please provide the text from your active layout.txt file?

**Comment by moosey-moose** [comment]
> Is this on a personal machine or one provided by an employer/organization?
> 
> The App could be crashing, or it may be getting stopped due to security concerns.
> 
> If the App is crashing, there could be corruption in the V-Drive, causing the App to break, or programming that is breaking the App.
> 
> Can you please provide the text from your active layout.txt file?

It is a personal machine and I just got the keyboard a week ago or so.

Edit: I'll also add that I tried running as administrator as well, with no change.

```
<base>
[spc]>[bspc]
[bspc]>[spc]
{lctr}{hk3}>{x1}{-rshf}{-rwin}{s}{+rshf}{+rwin}

<keypad>

<function1>

<function2>

<function3>
```

**Comment by moosey-moose** [comment]
My bad, it was my antivirus. Didn't get any popups.

**Comment by Omniscently** [comment]
Great to hear. 

Thanks for letting me know.
